### ISSUE TITLE
dotnet: Unable to determine root directory. Please run within google-cloud-dotnet repository

### ISSUE THREAD

**Issue by burkedavison** [googleapis/generator#68]
```
burkedavison@burkedavison:~/generator$ GENERATOR_CLI_REPOSITORY=us-central1-docker.pkg.dev/cloud-sdk-production-pipeline/pipeline-images
burkedavison@burkedavison:~/generator$ export GENERATOR_CLI_REPOSITORY
burkedavison@burkedavison:~/generator$ go run ./cmd/generator update-repo -language=dotnet
```

```
2024/12/17 03:17:25 INFO --------------------------------------------------------------------------------
2024/12/17 03:17:25 INFO /usr/bin/docker run -v /tmp/generator-20241217T031628/googleapis:/apis -v /tmp/generator-20241217T031628/output:/output -v /tmp/generator-20241217T031628/generator-input:/generator-input us-central1-docker.pkg.dev/cloud-sdk-production-pipeline/pipeline-images/google-cloud-dotnet-generator generate --api-root=/apis --output=/output --generator-input=/generator-input
2024/12/17 03:17:25 INFO --------------------------------------------------------------------------------
Failed: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Google.Cloud.Tools.Common.UserErrorException: Unable to determine root directory. Please run within google-cloud-dotnet repository.
   at Google.Cloud.Tools.Common.RootLayout.DetermineRootDirectory() in /src/tools/Google.Cloud.Tools.Common/RootLayout.cs:line 132
   at Google.Cloud.Tools.Common.RootLayout.ForCurrentDirectory() in /src/tools/Google.Cloud.Tools.Common/RootLayout.cs:line 83
   at Google.Cloud.Tools.ReleaseManager.CommandBase..ctor(String command, String description, Int32 minArgs, Int32 maxArgs, String expectedArguments) in /src/tools/Google.Cloud.Tools.ReleaseManager/CommandBase.cs:line 55
   at Google.Cloud.Tools.ReleaseManager.CommandBase..ctor(String command, String description, String[] argNames) in /src/tools/Google.Cloud.Tools.ReleaseManager/CommandBase.cs:line 59
   at Google.Cloud.Tools.ReleaseManager.AddPullRequestCommentCommand..ctor() in /src/tools/Google.Cloud.Tools.ReleaseManager/AddPullRequestCommentCommand.cs:line 31
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.CastIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Google.Cloud.Tools.ReleaseManager.Program.GetCommand(String[] args) in /src/tools/Google.Cloud.Tools.ReleaseManager/Program.cs:line 62
   at Google.Cloud.Tools.ReleaseManager.Program.Main(String[] args) in /src/tools/Google.Cloud.Tools.ReleaseManager/Program.cs:line 33
```

**Comment by jskeet** [comment]
This was fixed in #14006 - not sure how you still saw it so recently (old image?) but I'll close this until we know there's still something wrong...
